config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users
  resources :houses

  get '/checkeditems' => 'top#checkeditems', as: "checkeditems"
  get '/favoriteitems' => 'top#favoriteitems', as: "favoriteitems"
  get '/dislikeitems' => 'top#dislikeitems', as: "dislikeitems"

  root 'top#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/house.rb
class House < ApplicationRecord
  has_many :images, :dependent => :destroy
  accepts_nested_attributes_for :images, allow_destroy: true

  # attachment :image
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :house
  # attachment :image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :houses
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:account, :name])
  end
end

app/controllers/houses_controller.rb
class HousesController < ApplicationController

  def new
    @house = House.new
    @house.images.build
  end

  def create
    @house = House.new(house_params)
    @house.user_id = current_user.id
    if @house.save
    redirect_to house_path(@house)
    else
      render :new
    end
  end

  def edit
    @house = House.find(params[:id])
    0.times do
      image = @house.images.build
     end
  end

  def update
    @house = House.find(params[:id])
    if @house.update(house_params)
    redirect_to house_path(@house)
    else
      render :template => "houses/edit"
    end
  end

  def destroy
    @house = House.find(params[:id])
    @house.destroy
    redirect_to houses_path
  end

  def show
    @house = House.find(params[:id])

  end

  def index
    @houses = House.all
  end

  private

  def house_params
      params.require(:house).permit(:user_id,
                                    :size,
                                    :built,
                                    :numberofparking,
                                    :numberofstorage,
                                    :numberofwindow,
                                    :numberofgate,
                                    :descripofstorage,
                                    :sizeofparking,
                                    :typeofparking,
                                    :typeofhouse,
                                    :sunlight,
                                    :address,
                                    :powervalue,
                                    :balcony,
                                    :road,
                                    :cooker,
                                    :floor, #樓層
                                    :floormaterial,
                                    :typeofbuilding,
                                    :housestatus,
                                    :neighboar,
                                    :link,
                                    :clozet,
                                    :layout,
                                    :supplementary,
                                    :bed,
                                    :bath,
                                    :price,
                                    :pricesqft,
                                    :hoa,
                                    :latitude,
                                    :longitude,
                                    :bus,
                                    :showerhead,
                                    :diningbar,
                                    :drain,
                                    :elevator,
                                    :commonplace,
                                    :packagereceiver,
                                    :gym,
                                    :checked,
                                    :likeornot,
                                    images_attributes: [:id,
                                                        :imageurl,
                                                        :note,
                                                        :_destroy
                                                       ]
                                  )
    end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
    @houses = House.all
    @checkedhouses = House.where(:houses => { checked: 'true' } ).all
    @favoritehouses = House.where(:houses => { likeornot: 'Super Like' } ).all
    @dislikehouses = House.where(:houses => { likeornot: 'Dislike' } ).all
  end

  def checkeditems
    @houses = House.where(:houses => { checked: 'true' } ).all
  end

  def favoriteitems
    @houses = House.where(:houses => { likeornot: 'Super like' } ).all
  end

  def dislikeitems
    @houses = House.where(:houses => { likeornot: 'Dislike' } ).all
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])

  end

  def edit

  end

  def update

  end

  def destroy

  end

  private

  def user_params
    params.require(:user).permit(:name, :account, :gender, :birth, :country)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user
  end

  def link_to_add_fields(name, form, association, locals={})
    new_object = form.object.send(association).klass.new
    id = new_object.object_id
    fields = form.fields_for(association, new_object, child_index: id) do |builder|
      render(association.to_s.singularize + "_fields", form: builder)
    end
    link_to(name, '#', class: [locals[:class], "add_fields"], data: {id: id, fields: fields.gsub("\n", "")})
  end

  def url_with_protocol(url)
    /^http/i.match(url) ? url : "http://#{url}"
  end
end

app/helpers/houses_helper.rb
module HousesHelper
  def currency(value)
    number_to_currency(value)
  end

  def size(value)
    number_with_delimiter(value, :delimiter => ',')
  end
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/houses/_form.html.erb
<div class="container">
<%= form_with(model: house, local: true) do |form| %>
  <div class="row">
    <div class="form-group col-sm-12">
      <%= form.label :Link %>
      <%= form.text_field :link, class:"form-control" %>
    </div>
    <div class="form-group col-md-12">
      <%= form.label :Images%>
      <%= form.fields_for :images do |builder| %>
        <%= render "image_fields", form: builder %>
      <% end %>
      <%= link_to_add_fields "+", form, :images, class: "btn btn-primary btn-sm" %>
    </div>
    <div class="form-group col-md-12">
      <%= form.label :Address %>
      <%= form.text_field :address, class:"form-control" %>
    </div>
    <div class="form-group col-md-3">
      <%= form.label :Type %><br/>
      <%= form.select :typeofhouse, [ 'Townhouse', 'Condo' ], :prompt => 'Select One' %>
    </div>
    <div class="form-group col-md-3">
      <%= form.label :"House Status" %><br />
      <%= form.select :housestatus, [ 'Sold', 'Has buyers', 'On sale' ], :prompt => 'Select One' %>
    </div>
    <div class="form-group col-md-3">
      <%= form.label :"Type of the building" %><br />
      <%= form.select :typeofbuilding, [ 'Roof', 'Box' ], :prompt => 'Select One' %>
    </div>
  </div>
  <div class="row">
    <div class="form-group col-md-3">
      <%= form.label :Size %>
      <%= form.text_field :size, class:"form-control" %>
    </div>
    <div class="form-group col-md-3">
      <%= form.label :Price %>
      <%= form.text_field :price, class:"form-control" %>
    </div>
    <div class="form-group col-md-3">
      <%= form.label :"Price/sqft" %>
      <%= form.text_field :pricesqft, class:"form-control" %>
    </div>
    <div class="form-group col-md-3">
      <%= form.label :HOA %>
      <%= form.text_field :hoa, class:"form-control" %>
    </div>
  </div>
  <div class="row">
    <div class="form-group col-md-4">
      <%= form.label :"Built Year" %>
      <%= form.text_field :built, class:"form-control" %>
    </div>
    <div class="form-group col-md-4">
      <%= form.label :"Number of Beds" %>
      <%= form.text_field :bed, class:"form-control" %>
    </div>
    <div class="form-group col-md-4">
      <%= form.label :"Number of Bath" %>
      <%= form.text_field :bath, class:"form-control" %>
    </div>
  </div>
  <div class="row">
    <div class="form-group col-md-4">
      <%= form.label :"Number of Parking" %>
      <%= form.number_field :numberofparking, class:"form-control", :size => 3 %>
    </div>
    <div class="form-group col-md-4">
      <%= form.label :"Parking Size" %>
      <%= form.text_field :sizeofparking, class:"form-control" %>
    </div>
    <div class="form-group col-md-4">
      <%= form.label :"Parking Type" %><br />
      <%= form.select :typeofparking, [ 'None', 'Garage', 'Common Parking' ], :prompt => 'Select One' %>
    </div>
  </div>
  <div class="row">
    <div class="form-group col-md-3">
      <%= form.label :"Number of gate" %><br/>
      <%= form.select :numberofgate, [ '1', '2', '3', '4' ], :prompt => 'Select One' %>
    </div>
    <div class="form-group col-md-3">
      <%= form.label :"Number of window" %><br/>
      <%= form.select :numberofwindow, [ '1', '2', '3', '4', '5', '6', '7', '8', '9', '10' ], :prompt => 'Select One' %>
    </div>
  </div>
  <div class="row">
    <div class="form-group col-md-3">
      <%= form.label :"Number of storage" %><br/>
      <%= form.select :numberofstorage, [ '1', '2', '3', '4' ], :prompt => 'Select One' %>
    </div>
    <div class="form-group col-md-3">
      <%= form.label :"Description of the storage" %>
      <%= form.text_field :descripofstorage, class:"form-control" %>
    </div>
  </div>
  <div class="row">
    <div class="form-group col-md-3">
      <%= form.label :"Showerhead ?" %>
      <%= form.label :showerhead, "Fixed", :value => "true"  %>
      <%= form.radio_button :showerhead, true %>
      <%= form.label :showerhead, "Flexible", :value => "false" %>
      <%= form.radio_button :showerhead, false %>
    </div>
    <div class="form-group col-md-3">
      <%= form.label :"Dining Bar ?" %>
      <%= form.label :diningbar, "Yes", :value => "true"  %>
      <%= form.radio_button :diningbar, true %>
      <%= form.label :diningbar, "No", :value => "false" %>
      <%= form.radio_button :diningbar, false %>
    </div>
    <div class="form-group col-md-3">
      <%= form.label :"Drain ?" %>
      <%= form.label :drain, "Yes", :value => "true"  %>
      <%= form.radio_button :drain, true %>
      <%= form.label :drain, "No", :value => "false" %>
      <%= form.radio_button :drain, false %>
    </div>
    <div class="form-group col-md-3">
      <%= form.label :"Elevator ?" %>
      <%= form.label :elevator, "Yes", :value => "true"  %>
      <%= form.radio_button :elevator, true %>
      <%= form.label :elevator, "No", :value => "false" %>
      <%= form.radio_button :elevator, false %>
    </div>
    <div class="form-group col-md-3">
      <%= form.label :"Commonplace ?" %>
      <%= form.label :commonplace, "Yes", :value => "true"  %>
      <%= form.radio_button :commonplace, true %>
      <%= form.label :commonplace, "No", :value => "false" %>
      <%= form.radio_button :commonplace, false %>
    </div>
    <div class="form-group col-md-3">
      <%= form.label :"Package receiver ?" %>
      <%= form.label :packagereceiver, "Yes", :value => "true"  %>
      <%= form.radio_button :packagereceiver, true %>
      <%= form.label :packagereceiver, "No", :value => "false" %>
      <%= form.radio_button :packagereceiver, false %>
    </div>
    <div class="form-group col-md-3">
      <%= form.label :"Gym ?" %>
      <%= form.label :gym, "Yes", :value => "true"  %>
      <%= form.radio_button :gym, true %>
      <%= form.label :gym, "No", :value => "false" %>
      <%= form.radio_button :gym, false %>
    </div>
    <div class="form-group col-md-3">
      <%= form.label :"Bus ?"%>
      <%= form.label :bus, "Yes", :value => "true"  %>
      <%= form.radio_button :bus, true %>
      <%= form.label :bus, "No", :value => "false" %>
      <%= form.radio_button :bus, false %>
    </div>
  </div>
  <div class="row">
    <div class="form-group col-md-3">
      <%= form.label :"Balcony" %>
      <%= form.text_field :balcony, class:"form-control" %>
    </div>
    <div class="form-group col-md-3">
      <%= form.label :"Road in front of the building" %>
      <%= form.text_field :road, class:"form-control" %>
    </div>
    <div class="form-group col-md-3">
      <%= form.label :"Cookers" %>
      <%= form.text_field :cooker, class:"form-control" %>
    </div>
    <div class="form-group col-md-3">
      <%= form.label :"Floor" %>
      <%= form.text_field :floor, class:"form-control" %>
    </div>
    <div class="form-group col-md-3">
      <%= form.label :"Floor Material" %>
      <%= form.text_field :floormaterial, class:"form-control" %>
    </div>
    <div class="form-group col-md-3">
      <%= form.label :"Power Value" %>
      <%= form.text_field :powervalue, class:"form-control" %>
    </div>
    <div class="form-group col-md-3">
      <%= form.label :Sunlight %>
      <%= form.text_field :sunlight, class:"form-control" %>
    </div>
    <div class="form-group col-md-3">
      <%= form.label :clozet %>
      <%= form.text_area :clozet, class:"form-control" %>
    </div>
    <div class="form-group col-md-3">
      <%= form.label :Neighbor %>
      <%= form.text_area :neighboar, class:"form-control" %>
    </div>
    <div class="form-group col-md-3">
      <%= form.label :Layout %>
      <%= form.text_area :layout, class:"form-control" %>
    </div>
    <div class="form-group col-md-3">
      <%= form.label :"Any supplementary ?" %>
      <%= form.text_area :supplementary, class:"form-control" %>
    </div>
  </div>
  <div class="row">
    <div class="form-group col-md-3">
      <%= form.label :"Checked ?" %>
      <%= form.label :checked, "Yes", :value => "true"  %>
      <%= form.radio_button :checked, true %>
      <%= form.label :checked, "No", :value => "false" %>
      <%= form.radio_button :checked, false %>
    </div>
    <div class="form-group col-md-3">
      <%= form.label :"Like or not ?" %>
      <%= form.select :likeornot, [ 'Super Like', 'Like', 'Normal', 'Dislike' ], :prompt => 'Select One' %>
    </div>
  </div>
  <div class="row">
    <div class="form-group col-md-12">
      <%= form.submit "Save", class:"btn btn-success" %>　
      <%= link_to 'Unsave', houses_path, class:"btn btn-danger"%>
    </div>
  </div>
<% end %>
</div>

app/views/houses/_image_fields.html.erb
<fieldset>
		<%= form.text_field :imageurl, placeholder: "image url", class: "form-control" %>
		<%= form.text_field :note, placeholder: "description", class: "form-control" %>
		<%= form.hidden_field :_destroy %>
		<%= link_to '#', class: "remove_fields" do%>Delete<% end %>
</fieldset>

app/views/houses/create.html.erb
<h1>Houses#create</h1>
<p>Find me in app/views/houses/create.html.erb</p>

app/views/houses/destroy.html.erb
<h1>Houses#destroy</h1>
<p>Find me in app/views/houses/destroy.html.erb</p>

app/views/houses/edit.html.erb
<%= render 'form', house: @house %>

app/views/houses/index.html.erb
<div class="container">
  <div class="row">
    <table class="table">
      <thead class="thead-dark">
        <tr>
          <th scope="col">#</th>
          <th scope="col">Checked?</th>
          <th scope="col">Like?</th>
          <th scope="col">Location</th>
          <th scope="col">Type</th>
          <th scope="col">Price</th>
          <th scope="col">Size(Sqft)</th>
          <th scope="col">Beds/Baths</th>
          <th scope="col">Handle</th>
        </tr>
      </thead>
      <tbody>
        <% @houses.first(20).each do |h| %>
          <tr>
            <td><%= h.id %></td>
            <td><%= h.likeornot %></td>
            <td><%= h.checked? ? 'o' : 'x'%></td>
            <td>
              <% if h.address.include?("98107") %>
                Ballard
              <% elsif h.address.include?("98117") %>
                Ballard
              <% elsif h.address.include?("98103") %>
                Fremont
              <% elsif h.address.include?("98119") %>
                North Queen Ann
              <% elsif h.address.include?("98109") %>
                East Queen Ann
              <% else %>
                <%= h.address %>
              <% end %>
            </td>
            <td><%= h.typeofhouse %></td>
            <td><%= currency(h.price) %></td>
            <td><%= size(h.size) %></td>
            <td><%= h.bed %> / <%= h.bath %></td>
            <td>
              <%= link_to "Show", house_path(h.id) %>
              <%= link_to "Edit", edit_house_path(h.id) %>
              <%= link_to("Delete", house_path(h.id), method: :delete, data: { confirm: "Are you sure?"}) %>
            </td>
          </tr>
        <%end%>
      </tbody>
    </table>
  </div>
</div>

app/views/houses/new.html.erb
<%= render 'form', house: @house %>

app/views/houses/update.html.erb
<h1>Houses#update</h1>
<p>Find me in app/views/houses/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Housing</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css'  %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light navbar-fixed-top">
      <a class="navbar-brand" href="#"></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <%= link_to root_path, class:"nav-link" do %>HOME<% end %>
            <span class="sr-only">(current)</span>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              MY LIST
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%= link_to houses_path, class:"dropdown-item" do %>ALL ITEMS<% end %>
              <%= link_to checkeditems_path, class:"dropdown-item" do %>CHECKED ITEMS<% end %>
              <%= link_to favoriteitems_path, class:"dropdown-item" do %>FAVORTIE ITEMS<% end %>
              <%= link_to dislikeitems_path, class:"dropdown-item" do %>HATE ITEMS<% end %>
            </div>

          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              SETTINGS
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%= link_to edit_user_path(current_user), class:"dropdown-item" do %>PROFILE<% end %>
              <div class="dropdown-divider"></div>
              <%= link_to edit_user_registration_path, class:"dropdown-item" do %>CHANGE PWD<% end %>
            </div>
          </li>
          <li class="nav-item">
              <%= link_to destroy_user_session_path, class:"nav-link", method: :delete do %>LOGOUT<% end %>
          </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/top/checkeditems.html.erb
<div class="container">
  <div class="row">
    <table class="table">
      <thead class="thead-dark">
        <tr>
          <th scope="col">#</th>
          <th scope="col">Like?</th>
          <th scope="col">Location</th>
          <th scope="col">Type</th>
          <th scope="col">Price</th>
          <th scope="col">Size(Sqft)</th>
          <th scope="col">Beds/Baths</th>
          <th scope="col">Handle</th>
        </tr>
      </thead>
      <tbody>
        <% @houses.each do |h| %>
          <tr>
            <td><%= h.id %></td>
            <td><%= h.likeornot %></td>
            <td>
              <% if h.address.include?("98107" || "98117") %>
                Ballard
              <% elsif h.address.include?("98103") %>
                Fremont
              <% elsif h.address.include?("98119") %>
                North Queen Ann
              <% elsif h.address.include?("98109") %>
                East Queen Ann
              <% else %>
                <%= h.address %>
              <% end %>
            </td>
            <td><%= h.typeofhouse %></td>
            <td><%= currency(h.price) %></td>
            <td><%= h.size %></td>
            <td><%= h.bed %> / <%= h.bath %></td>
            <td>
              <%= link_to "Show", house_path(h.id) %>
              <%= link_to "Edit", edit_house_path(h.id) %>
              <%= link_to("Delete", house_path(h.id), method: :delete, data: { confirm: "Are you sure?"}) %>
            </td>
          </tr>
        <%end%>
      </tbody>
    </table>
  </div>
</div>

app/views/top/dislikeitems.html.erb
<div class="container">
  <div class="row">
    <table class="table">
      <thead class="thead-dark">
        <tr>
          <th scope="col">#</th>
          <th scope="col">Location</th>
          <th scope="col">Type</th>
          <th scope="col">Price</th>
          <th scope="col">Size(Sqft)</th>
          <th scope="col">Beds/Baths</th>
          <th scope="col">Handle</th>
        </tr>
      </thead>
      <tbody>
        <% @houses.first(20).each do |h| %>
          <tr>
            <td><%= h.id %></td>
            <td>
              <% if h.address.include?("98107") %>
                Ballard
              <% elsif h.address.include?("98117") %>
                Ballard
              <% elsif h.address.include?("98103") %>
                Fremont
              <% elsif h.address.include?("98119") %>
                North Queen Ann
              <% elsif h.address.include?("98109") %>
                East Queen Ann
              <% else %>
                <%= h.address %>
              <% end %>
            </td>
            <td><%= h.typeofhouse %></td>
            <td><%= currency(h.price) %></td>
            <td><%= size(h.size) %></td>
            <td><%= h.bed %> / <%= h.bath %></td>
            <td>
              <%= link_to "Show", house_path(h.id) %>
              <%= link_to "Edit", edit_house_path(h.id) %>
              <%= link_to("Delete", house_path(h.id), method: :delete, data: { confirm: "Are you sure?"}) %>
            </td>
          </tr>
        <%end%>
      </tbody>
    </table>
  </div>
</div>

app/views/top/favoriteitems.html.erb
<div class="container">
  <div class="row">
    <table class="table">
      <thead class="thead-dark">
        <tr>
          <th scope="col">#</th>
          <th scope="col">Location</th>
          <th scope="col">Type</th>
          <th scope="col">Price</th>
          <th scope="col">Size(Sqft)</th>
          <th scope="col">Beds/Baths</th>
          <th scope="col">Handle</th>
        </tr>
      </thead>
      <tbody>
        <% @houses.first(20).each do |h| %>
          <tr>
            <td><%= h.id %></td>
            <td><%= h.checked? ? 'o' : 'x'%></td>
            <td>
              <% if h.address.include?("98107") %>
                Ballard
              <% elsif h.address.include?("98117") %>
                Ballard
              <% elsif h.address.include?("98103") %>
                Fremont
              <% elsif h.address.include?("98119") %>
                North Queen Ann
              <% elsif h.address.include?("98109") %>
                East Queen Ann
              <% else %>
                <%= h.address %>
              <% end %>
            </td>
            <td><%= h.typeofhouse %></td>
            <td><%= currency(h.price) %></td>
            <td><%= size(h.size) %></td>
            <td><%= h.bed %> / <%= h.bath %></td>
            <td>
              <%= link_to "Show", house_path(h.id) %>
              <%= link_to "Edit", edit_house_path(h.id) %>
              <%= link_to("Delete", house_path(h.id), method: :delete, data: { confirm: "Are you sure?"}) %>
            </td>
          </tr>
        <%end%>
      </tbody>
    </table>
  </div>
</div>

app/views/top/index.html.erb
<div class="container">
  <div class="row p-20">
    <!-- Total -->
    <div class="col-md-3">
      <div class="card bg-c-yellow">
          <div class="card-block">
              <div class="row align-items-end">
                  <div class="col-12">
                      <h6 class="m-l-10 m-t-5 text-white">Total items I saved</h6>
                      <h4 class="m-l-10 text-white"><%= @houses.count%> items</h4>
                  </div>
              </div>
          </div>
          <div class="card-footer">
              <%= link_to houses_path, class: "text-white pull-right" do %>Learn More...<% end %>
          </div>
      </div>
    </div>
    <!-- The items I have checked -->
    <div class="col-md-3">
      <div class="card bg-c-green">
          <div class="card-block">
              <div class="row align-items-end">
                  <div class="col-12">
                      <h6 class="m-l-10 m-t-5 text-white">Checked Items</h6>
                      <h4 class="m-l-10 text-white"><%= @checkedhouses.count%> items</h4>
                  </div>
              </div>
          </div>
          <div class="card-footer">
              <%= link_to checkeditems_path, class: "text-white pull-right" do %>Learn More...<% end %>
          </div>
      </div>
    </div>
    <!-- Favorite Items -->
    <div class="col-md-3">
      <div class="card bg-c-pink">
          <div class="card-block">
              <div class="row align-items-end">
                  <div class="col-12">
                      <h6 class="m-l-10 m-t-5 text-white">Favorite Items</h6>
                      <h4 class="m-l-10 text-white"><%= @favoritehouses.count%> items</h4>
                  </div>
              </div>
          </div>
          <div class="card-footer">
              <%= link_to favoriteitems_path, class: "text-white pull-right" do %>Learn More...<% end %>
          </div>
      </div>
    </div>
    <!-- Black List -->
    <div class="col-md-3">
      <div class="card bg-c-blue">
          <div class="card-block">
              <div class="row align-items-end">
                  <div class="col-12">
                      <h6 class="m-l-10 m-t-5 text-white">Black List</h6>
                      <h4 class="m-l-10 text-white"><%= @dislikehouses.count%> items</h4>
                  </div>
              </div>
          </div>
          <div class="card-footer">
              <%= link_to dislikeitems_path, class: "text-white pull-right" do %>Learn More...<% end %>
          </div>
      </div>
    </div>
 </div>
 <hr>
</div>
<div class="container">
  <div class="row">
    <div style="margin:0 auto;">
      <iframe src="https://www.google.com/maps/d/u/0/embed?mid=103WdlPB8xaPRmSRaW_fiWMyvlviSr53v" width="640" height="480"></iframe>
    </div>
  </div>
</div>